export const ERROR_TYPE_FIELDS = "ERROR_TYPE_FIELDS"
export const UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
export const ERROR_MESSAGE = "ERROR_MESSAGE"
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"